services:
  postgres:
    image: postgres:17-alpine
    container_name: event-booking-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_booking
    ports:
      - "5544:5432"
    volumes:
      - event-booking-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: event-booking-redis
    restart: unless-stopped
    ports:
      - "6390:6379"
    volumes:
      - event-booking-redis-data:/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: event-booking-mailpit
    restart: unless-stopped
    ports:
      - "1026:1025" # SMTP
      - "8026:8025" # Web UI

volumes:
  event-booking-postgres-data:
  event-booking-redis-data:
